version: "3"

services:
    db:
        image: postgis/postgis:latest
        platform: 'linux/amd64'
        restart: always
        environment:
            - POSTGRES_DB=${DATABASE_DB}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - ./data/database:/var/lib/postgresql/data
        ports:
            - "${DATABASE_PORT_OUT}:5432"

